### ISSUE TITLE
noclip keybind in F2

### ISSUE THREAD

**Issue by DARKAOFF** [BerkieBb/bMenu#3]
is it possible to put the noclip keybind in F2 and the number of online players in online player

thanking you very much

**Comment by BerkieBb** [comment]
The number of online players in online player has been done in this commit https://github.com/BerkieBb/bMenu/commit/bfa2bf61b8bb5e71c73a3b50c4227366c10288cf

**Comment by BerkieBb** [comment]
And the noclip keybind has been added here https://github.com/BerkieBb/bMenu/commit/a16fde3bb177c5e4e3554f6ffe14b701dbdf3410
